### ISSUE TITLE
A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#1634]
in edit or create proutct.

```
System.NotSupportedException: A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at SmartStore.Data.ObjectContextBase.SaveChangesCore() in D:\store\ver3.2\src\Libraries\SmartStore.Data\ObjectContextBase.SaveChanges.cs:line 121
   at SmartStore.Data.ObjectContextBase.SaveChangesOperation.Execute() in D:\store\ver3.2\src\Libraries\SmartStore.Data\ObjectContextBase.SaveChanges.cs:line 247
   at SmartStore.Data.ObjectContextBase.SaveChanges() in D:\store\ver3.2\src\Libraries\SmartStore.Data\ObjectContextBase.SaveChanges.cs:line 74
   at SmartStore.Data.EfRepository`1.Update(T entity) in D:\store\ver3.2\src\Libraries\SmartStore.Data\EfRepository.cs:line 144
   at SmartStore.Services.Catalog.ProductService.UpdateProduct(Product product) in D:\store\ver3.2\src\Libraries\SmartStore.Services\Catalog\ProductService.cs:line 304
   at SmartStore.Admin.Controllers.ProductController.UpdateDataOfExistingProduct(Product product, ProductModel model, Boolean editMode) in D:\store\ver3.2\src\Presentation\SmartStore.Web\Administration\Controllers\ProductController.cs:line 568
   at SmartStore.Admin.Controllers.ProductController.Edit(ProductModel model, Boolean continueEditing, FormCollection form) in D:\store\ver3.2\src\Presentation\SmartStore.Web\Administration\Controllers\ProductController.cs:line 1305
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
```

**Comment by Michael-Herzog** [comment]
We're currently researching this with the highest priority.
