### ISSUE TITLE
NullReferenceException in Update catalog search index

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#1928]
We noticed that sometimes the scheduled task of "Update catalog search index" reports an error. We did some debugging but didn't find cause of it. 

Full error message:
```
Error:  System.AggregateException: AsyncHelpers.Run method threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SmartStore.Web.Framework.UI.Menus.Providers.CatalogMenuInvalidator.ResetElementCounts(String menuName) in C:\WebSites\SmartStoreNET-3.2.2\src\Presentation\SmartStore.Web.Framework\UI\Menus\Providers\CatalogMenuInvalidator.cs:line 78
   at SmartStore.Web.Framework.UI.Menus.Providers.CatalogMenuInvalidator.d__7.MoveNext() in C:\WebSites\SmartStoreNET-3.2.2\src\Presentation\SmartStore.Web.Framework\UI\Menus\Providers\CatalogMenuInvalidator.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SmartStore.Core.Async.AsyncRunner.<>c__DisplayClass7_0.<b__0>d.MoveNext() in C:\WebSites\SmartStoreNET-3.2.2\src\Libraries\SmartStore.Core\Async\AsyncRunner.cs:line 70
   --- End of inner exception stack trace ---
   at SmartStore.Core.Events.ConsumerInvoker.HandleException(Exception ex, ConsumerDescriptor descriptor) in C:\WebSites\SmartStoreNET-3.2.2\src\Libraries\SmartStore.Core\Events\ConsumerInvoker.cs:line 116
   at SmartStore.Core.Events.ConsumerInvoker.Invoke[TMessage](ConsumerDescriptor descriptor, IConsumer consumer, ConsumeContext`1 envelope) in C:\WebSites\SmartStoreNET-3.2.2\src\Libraries\SmartStore.Core\Events\ConsumerInvoker.cs:line 42
   at SmartStore.Services.Events.EventPublisher.Publish[T](T message) in C:\WebSites\SmartStoreNET-3.2.2\src\Libraries\SmartStore.Services\Events\EventPublisher.cs:line 46
   at SmartStore.MegaSearch.Services.DefaultIndexingService.BuildIndexInternal(String scope, TaskExecutionContext taskContext, Boolean rebuild, Boolean continueRebuild)
   at SmartStore.MegaSearch.Services.DefaultIndexingService.BuildIndex(String scope, TaskExecutionContext context, String command)
   at SmartStore.MegaSearch.IndexingTask.Execute(TaskExecutionContext context)
   at SmartStore.Services.Tasks.TaskExecutor.d__16.MoveNext() in C:\WebSites\SmartStoreNET-3.2.2\src\Libraries\SmartStore.Services\Tasks\TaskExecutor.cs:line 132
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at SmartStore.Web.Framework.UI.Menus.Providers.CatalogMenuInvalidator.ResetElementCounts(String menuName) in C:\WebSites\SmartStoreNET-3.2.2\src\Presentation\SmartStore.Web.Framework\UI\Menus\Providers\CatalogMenuInvalidator.cs:line 78
   at SmartStore.Web.Framework.UI.Menus.Providers.CatalogMenuInvalidator.d__7.MoveNext() in C:\WebSites\SmartStoreNET-3.2.2\src\Presentation\SmartStore.Web.Framework\UI\Menus\Providers\CatalogMenuInvalidator.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SmartStore.Core.Async.AsyncRunner.<>c__DisplayClass7_0.<b__0>d.MoveNext() in C:\WebSites\SmartStoreNET-3.2.2\src\Libraries\SmartStore.Core\Async\AsyncRunner.cs:line 70<---
```

Scheduled task History tab:
![image](https://user-images.githubusercontent.com/64465421/83609532-baffa580-a57e-11ea-9f83-2f9579d7ac27.png)

Log window:
![image](https://user-images.githubusercontent.com/64465421/83609748-f9956000-a57e-11ea-8b60-bed937c6f079.png)

Error 1 Detailed:
![image](https://user-images.githubusercontent.com/64465421/83609858-1af64c00-a57f-11ea-863a-e1fed89b188e.png)

Error 2 Detailed:
![image](https://user-images.githubusercontent.com/64465421/83609913-29dcfe80-a57f-11ea-82c5-c3b17d9afe09.png)

**Comment by TripleNico** [comment]
Thanks for fixing this so quickly!
