### ISSUE TITLE
Rebuild XML Sitemap System.NullReferenceException

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#2117]
after update to 4.0.1

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SmartStore.Services.Seo.XmlSitemapProvider.CreateNode(UrlHelper urlHelper, String baseUrl, NamedEntity entity, UrlRecordCollection slugs, Language language) in D:\Store\Ver4\SmartStoreNET\src\Libraries\SmartStore.Services\Seo\IXmlSitemapPublisher.cs:line 35
   at SmartStore.Services.Seo.XmlSitemapGenerator.<>c__DisplayClass27_2.<RebuildAsync>b__6(NodeEntry x) in D:\Store\Ver4\SmartStoreNET\src\Libraries\SmartStore.Services\Seo\XmlSitemapGenerator.cs:line 305
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at SmartStore.CollectionExtensions.AddRange[T](ICollection`1 initial, IEnumerable`1 other) in D:\Store\Ver4\SmartStoreNET\src\Libraries\SmartStore.Core\Extensions\CollectionExtensions.cs:line 17
   at SmartStore.Services.Seo.XmlSitemapGenerator.<RebuildAsync>d__27.MoveNext() in D:\Store\Ver4\SmartStoreNET\src\Libraries\SmartStore.Services\Seo\XmlSitemapGenerator.cs:line 306
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SmartStore.Services.Seo.RebuildXmlSitemapTask.<ExecuteAsync>d__5.MoveNext() in D:\Store\Ver4\SmartStoreNET\src\Libraries\SmartStore.Services\Seo\Tasks\RebuildXmlSitemapTask.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SmartStore.Services.Tasks.TaskExecutor.<ExecuteAsync>d__16.MoveNext() in D:\Store\Ver4\SmartStoreNET\src\Libraries\SmartStore.Services\Tasks\TaskExecutor.cs:line 128
```

**Comment by mgesing** [comment]
Unfortunately I cannot reproduce the error. Have you ever debugged this?

**Comment by pineportal** [comment]
It is difficult to debug this site.I'm trying to debug.
I will announce the result later

**Comment by pineportal** [comment]
one product deleted slug.
