### ISSUE TITLE
PayPal Error ( PayPalCheckoutState.PaypalOrderId )

### ISSUE THREAD

**Issue by AresDraco** [smartstore/SmartStoreNET#2263]
I'm running SmartStore 5.0.0
Using the plugin Paypal 5.0
Versión: 5.0  Autor: SmartStore AG  Nombre del sistema.: Smartstore.PayPal

When trying to place an order and pressing the confirm button at the https://www.misuperdespensa.com/checkout/confirm/ webpage I get the error below:

"Falta el estado de la sesión de pago ( PayPalCheckoutState.PaypalOrderId ). Lo sentimos, su pago no puede ser procesado. Por favor, vuelva a la cesta de la compra y pase de nuevo por la caja."

and this is what I get at the Log file:

Smartstore.PayPal.Client.PayPalException: Falta el estado de la sesión de pago ( PayPalCheckoutState.PaypalOrderId ). Lo sentimos, su pago no puede ser procesado. Por favor, vuelva a la cesta de la compra y pase de nuevo por la caja.
   at Smartstore.PayPal.Providers.PayPalStandardProvider.ProcessPaymentAsync(ProcessPaymentRequest request)
   at Smartstore.Core.Checkout.Payment.PaymentService.ProcessPaymentAsync(ProcessPaymentRequest processPaymentRequest) in D:\Git\Smartstore.Full\Smartstore\src\Smartstore.Core\Checkout\Payment\Service\PaymentService.cs:line 245
   at Smartstore.Core.Checkout.Orders.OrderProcessingService.ProcessPayment(PlaceOrderContext ctx) in D:\Git\Smartstore.Full\Smartstore\src\Smartstore.Core\Checkout\Orders\Services\OrderProcessingService.PlaceOrder.cs:line 595
   at Smartstore.Core.Checkout.Orders.OrderProcessingService.PlaceOrderAsync(ProcessPaymentRequest paymentRequest, Dictionary`2 extraData) in D:\Git\Smartstore.Full\Smartstore\src\Smartstore.Core\Checkout\Orders\Services\OrderProcessingService.PlaceOrder.cs:line 69
   at Smartstore.Web.Controllers.CheckoutController.ConfirmOrder() in D:\Git\Smartstore.Full\Smartstore\src\Smartstore.Web\Controllers\CheckoutController.cs:line 658

any ideas? thx in advance.

**Comment by Michael-Herzog** [comment]
Please upgrade to the latest version by using the branch 5.0.1.x
